version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: visao360_postgres
    environment:
      POSTGRES_USER: visao360
      POSTGRES_PASSWORD: visao360_pass
      POSTGRES_DB: visao360
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U visao360']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: visao360_redis
    command: redis-server --appendonly yes --requirepass "redis_pass_visao360"
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--no-auth-warning', '-a', 'redis_pass_visao360', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
